services:
  nginx:
    ports:
      - "80:80"
    build:
      target: prod
  node-app:
    build:
      context: .
      target: prod
    ports:
      - "3000:3000"
  postgres:
    ports:
      - "5432:5432"
