version: "3"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app

  node-app:
    build: .
    deploy:
      replicas: 2
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres
    user: postgres
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
      - "./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql"
    restart: always

volumes:
  db:
    driver: local
